### ISSUE TITLE
API de datos del portal requiere links

### ISSUE THREAD

**Issue by avdata99** [ModernizacionMuniCBA/dendrograma-datos-abiertos-cordoba#3]
Para resolver #1 necesitamos que el API de datos entregue las URLs en los recursos de datos que son simplemente links. En la imagen el recurso KML esta OK pero el que es link esta como _null_.

![image](https://user-images.githubusercontent.com/3237309/42278622-d5cf0246-7f71-11e8-801e-edb1aab81052.png)

**Comment by avdata99** [comment]
Esto ya está Maycol?
Creo que si. Confirmá y cerrá si es así

**Comment by wilmays10** [comment]
Si, ya está hecho desde [Qhapax](https://github.com/avdata99/Qhapax/issues/1592) .

**Comment by avdata99** [comment]
Te olvidaste de cerrar acá!
